<?php
// -----
// Part of the One-Page Checkout plugin, provided under GPL 2.0 license by lat9 (cindy@vinosdefrutastropicales.com).
// Copyright (C) 2017-2022, Vinos de Frutas Tropicales.  All rights reserved.
//
// This module is included by tpl_modules_opc_billing_address.php and tpl_modules_opc_shipping_address.php and
// provides a common-formatting for those two address-blocks.
//
// Last updated: OPC v2.4.2/Bootstrap v5.0.0
//
// -----
// Sanitize module input values.
//
if (!isset($opc_address_type) || !in_array($opc_address_type, ['bill', 'ship'])) {
    trigger_error("Unknown value for opc_address_type ($opc_address_type).", E_USER_ERROR);
    exit();
}

// -----
// Start address formatting ...
//
$which = $opc_address_type;
$address = $_SESSION['opc']->getAddressValues($which);
if ($address['validated']) {
    $display_condensed_address = true;
    $address_form_class = ' class="d-none"';
} else {
    $display_condensed_address = false;
    $address_form_class = '';
}

// -----
// Create a variable that can be used in all form-entry fields below to add a clearing break to the display.
//
// Note: For the bootstrap template's use, we'll turn this into a simply spacing div.
//
$clear_both = '<div class="mb-3"></div>';

// -----
// Indicate that the default parameters to apply to each label generated by $_SESSION['opc']->formatAddressEntry()
// should be ' class="form-label"', unless otherwise overridden.
//
$_SESSION['opc']->setAddressLabelParams(' class="form-label"');

// -----
// The first section of an address-block contains the condensed formatting of the address, to reduce
// on-screen real-estate required.
//
if ($display_condensed_address === true) {
?>
<div id="address-<?php echo $which; ?>" class="row">
    <div class="col-10"><?php echo zen_address_format(zen_get_address_format_id($address['country_id']), $address, true, '', '<br>'); ?></div>
<?php
if ($opc_disable_address_change === false) {
?>
    <div class="col-2 text-end" id="opc-<?php echo $which; ?>-edit"><?php echo zen_image_button(BUTTON_IMAGE_EDIT_SMALL, BUTTON_EDIT_SMALL_ALT, '', 'btn btn-secondary'); ?></div>
<?php
}
?>
</div>
<?php
}

// -----
// The second section contains the address-form through which an address can be changed, if enabled.  If the
// address can't be changed, perform a quick return so that the form elements aren't rendered.
//
if ($opc_disable_address_change === true) {
    return;
}
?>
<div id="address-form-<?php echo $which; ?>"<?php echo $address_form_class; ?>>
<?php
// -----
// If the address can be changed and an account-bearing customer has previously-defined addresses, create a dropdown list
// from which they can select.
//
// Note: Checking for more than two (2) entries, since the "Choose from previous selections" is
// pre-populated!
//
if ($opc_disable_address_change === false) {
    $address_selections = $_SESSION['opc']->formatAddressBookDropdown();
    if (count($address_selections) > 2) {
        $selected = $_SESSION['opc']->getAddressDropDownSelection($which);
?>
    <div id="choices-<?php echo $which; ?>" class="mb-3">
        <?php echo zen_draw_pull_down_menu("address-$which", $address_selections, $selected, 'class="form-select"'); ?>
    </div>
<?php
    }
}

if (ACCOUNT_GENDER === 'true') {
    $field_name = "gender[$which]";
    $male_id = "gender-male-$which";
    $female_id = "gender-female-$which";
?>
    <div class="mb-3">
        <span class="form-check form-check-inline">
            <?php echo zen_draw_radio_field($field_name, 'm', ($address['gender'] === 'm'), "id=\"$male_id\" class=\"form-check-input\""); ?>
            <label class="form-check-label" for="<?php echo $male_id; ?>"><?php echo MALE; ?></label>
        </span>
        <span class="form-check form-check-inline">
            <?php echo zen_draw_radio_field($field_name, 'f', ($address['gender'] === 'f'), "id=\"$female_id\" class=\"form-check-input\""); ?>
            <label class="form-check-label" for="<?php echo $female_id; ?>"><?php echo FEMALE; ?></label>
        </span>
        <?php echo (zen_not_null(ENTRY_GENDER_TEXT) ? '<span class="text-danger">' . ENTRY_GENDER_TEXT . '</span>' : ''); ?>
    </div>
<?php
}

echo '<div class="form-floating mb-3">';
echo $_SESSION['opc']->formatAddressElement($which, 'firstname', $address['firstname'], ENTRY_FIRST_NAME, TABLE_CUSTOMERS, 'customers_firstname', ENTRY_FIRST_NAME_MIN_LENGTH, ENTRY_FIRST_NAME_TEXT, 'class="form-control" placeholder="' . ENTRY_FIRST_NAME . '"');
echo '<label for="firstname-' . $which . '">' . ENTRY_FIRST_NAME . '</label>';
echo '</div>';

echo '<div class="form-floating mb-3">';
echo $_SESSION['opc']->formatAddressElement($which, 'lastname', $address['lastname'], ENTRY_LAST_NAME, TABLE_CUSTOMERS, 'customers_lastname', ENTRY_LAST_NAME_MIN_LENGTH, ENTRY_LAST_NAME_TEXT, 'class="form-control" placeholder="' . ENTRY_LAST_NAME . '"');
echo '<label for="lastname-' . $which . '">' . ENTRY_LAST_NAME . '</label>';
echo '</div>';

$field_name = "zone_country_id[$which]";
$field_id = "country-$which";
?>
<div class="form-floating mb-3">
    <?php echo zen_get_country_list($field_name, $address['country'], "id=\"$field_id\" class=\"form-select\""); ?>
    <label for="<?php echo $field_id; ?>"><?php echo ENTRY_COUNTRY; ?></label>
    <?php echo (zen_not_null(ENTRY_COUNTRY_TEXT) ? '<span class="text-danger">' . ENTRY_COUNTRY_TEXT . '</span>' : ''); ?>
</div>
<?php
if (ACCOUNT_STATE === 'true') {
    $state_zone_id = "stateZone-$which";
    $zone_field_name = "zone_id[$which]";
?>
<div class="form-floating mb-3">
    <?php
    if ($address['show_pulldown_states']) {
        echo zen_draw_pull_down_menu($zone_field_name, zen_prepare_country_zones_pull_down($address['country']), $address['zone_id'], "id=\"$state_zone_id\" class=\"form-select\"");
    } else {
        echo zen_draw_hidden_field($zone_field_name, $address['zone_name']);
    }
    ?>
    <label for="<?php echo $state_zone_id; ?>"><?php echo ENTRY_STATE; ?></label>
    <?php echo (zen_not_null(ENTRY_STATE_TEXT) ? '<span class="text-danger">' . ENTRY_STATE_TEXT . '</span>' : ''); ?>
</div>
<?php
    echo '<div class="form-floating mb-3">';
    echo $_SESSION['opc']->formatAddressElement($which, 'state', $address['state'], '', TABLE_ADDRESS_BOOK, 'entry_state', ENTRY_STATE_MIN_LENGTH, ENTRY_STATE_TEXT, 'class="form-control" placeholder="' . ENTRY_STATE . '"');
    echo '<label for="state-' . $which . '">' . ENTRY_STATE . '</label>';
    echo '</div>';
}

if (ACCOUNT_COMPANY === 'true') {
    echo '<div class="form-floating mb-3">';
    echo $_SESSION['opc']->formatAddressElement($which, 'company', $address['company'], ENTRY_COMPANY, TABLE_ADDRESS_BOOK, 'entry_company', ENTRY_COMPANY_MIN_LENGTH, ENTRY_COMPANY_TEXT, 'class="form-control" placeholder="' . ENTRY_COMPANY . '"');
    echo '<label for="company-' . $which . '">' . ENTRY_COMPANY . '</label>';
    echo '</div>';
}

echo '<div class="form-floating mb-3">';
echo $_SESSION['opc']->formatAddressElement($which, 'street_address', $address['street_address'], ENTRY_STREET_ADDRESS, TABLE_ADDRESS_BOOK, 'entry_street_address', ENTRY_STREET_ADDRESS_MIN_LENGTH, ENTRY_STREET_ADDRESS_TEXT, 'class="form-control" placeholder="' . ENTRY_STREET_ADDRESS . '"');
echo '<label for="street-address-' . $which . '">' . ENTRY_STREET_ADDRESS . '</label>';
echo '</div>';

if (ACCOUNT_SUBURB === 'true') {
    echo '<div class="form-floating mb-3">';
    echo $_SESSION['opc']->formatAddressElement($which, 'suburb', $address['suburb'], ENTRY_SUBURB, TABLE_ADDRESS_BOOK, 'entry_suburb', 0, ENTRY_SUBURB_TEXT, 'class="form-control" placeholder="' . ENTRY_SUBURB . '"');
    echo '<label for="suburb-' . $which . '">' . ENTRY_SUBURB . '</label>';
    echo '</div>';
}

echo '<div class="form-floating mb-3">';
echo $_SESSION['opc']->formatAddressElement($which, 'city', $address['city'], ENTRY_CITY, TABLE_ADDRESS_BOOK, 'entry_city', ENTRY_CITY_MIN_LENGTH, ENTRY_CITY_TEXT, 'class="form-control" placeholder="' . ENTRY_CITY . '"');
echo '<label for="city-' . $which . '">' . ENTRY_CITY . '</label>';
echo '</div>';

echo '<div class="form-floating mb-3">';
echo $_SESSION['opc']->formatAddressElement($which, 'postcode', $address['postcode'], ENTRY_POST_CODE, TABLE_ADDRESS_BOOK, 'entry_postcode', ENTRY_POSTCODE_MIN_LENGTH, ENTRY_POST_CODE_TEXT, 'class="form-control" placeholder="' . ENTRY_POST_CODE . '"');
echo '<label for="postcode-' . $which . '">' . ENTRY_POST_CODE . '</label>';
echo '</div>';
?>
<div id="messages-<?php echo $which; ?>" class="mt-3"></div>
</div>
